# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: macaroon.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='macaroon.proto',
  package='macaroons',
  serialized_pb=_b('\n\x0emacaroon.proto\x12\tmacaroons\"\xfb\x01\n\x08Macaroon\x12\n\n\x02id\x18\x01 \x02(\t\x12\x10\n\x08location\x18\x02 \x02(\t\x12+\n\x07\x63\x61veats\x18\x03 \x03(\x0b\x32\x1a.macaroons.Macaroon.Caveat\x12\x11\n\tsignature\x18\x04 \x02(\t\x1a\x61\n\x06\x43\x61veat\x12,\n\x04type\x18\x01 \x02(\x0e\x32\x1e.macaroons.Macaroon.CaveatType\x12\n\n\x02id\x18\x02 \x02(\t\x12\x10\n\x08location\x18\x03 \x01(\t\x12\x0b\n\x03vid\x18\x04 \x01(\t\".\n\nCaveatType\x12\x0f\n\x0b\x46IRST_PARTY\x10\x00\x12\x0f\n\x0bTHIRD_PARTY\x10\x01')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_MACAROON_CAVEATTYPE = _descriptor.EnumDescriptor(
  name='CaveatType',
  full_name='macaroons.Macaroon.CaveatType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='FIRST_PARTY', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='THIRD_PARTY', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=235,
  serialized_end=281,
)
_sym_db.RegisterEnumDescriptor(_MACAROON_CAVEATTYPE)


_MACAROON_CAVEAT = _descriptor.Descriptor(
  name='Caveat',
  full_name='macaroons.Macaroon.Caveat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='macaroons.Macaroon.Caveat.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='id', full_name='macaroons.Macaroon.Caveat.id', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='location', full_name='macaroons.Macaroon.Caveat.location', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='vid', full_name='macaroons.Macaroon.Caveat.vid', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=136,
  serialized_end=233,
)

_MACAROON = _descriptor.Descriptor(
  name='Macaroon',
  full_name='macaroons.Macaroon',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='macaroons.Macaroon.id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='location', full_name='macaroons.Macaroon.location', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='caveats', full_name='macaroons.Macaroon.caveats', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='signature', full_name='macaroons.Macaroon.signature', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_MACAROON_CAVEAT, ],
  enum_types=[
    _MACAROON_CAVEATTYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=281,
)

_MACAROON_CAVEAT.fields_by_name['type'].enum_type = _MACAROON_CAVEATTYPE
_MACAROON_CAVEAT.containing_type = _MACAROON
_MACAROON.fields_by_name['caveats'].message_type = _MACAROON_CAVEAT
_MACAROON_CAVEATTYPE.containing_type = _MACAROON
DESCRIPTOR.message_types_by_name['Macaroon'] = _MACAROON

Macaroon = _reflection.GeneratedProtocolMessageType('Macaroon', (_message.Message,), dict(

  Caveat = _reflection.GeneratedProtocolMessageType('Caveat', (_message.Message,), dict(
    DESCRIPTOR = _MACAROON_CAVEAT,
    __module__ = 'macaroon_pb2'
    # @@protoc_insertion_point(class_scope:macaroons.Macaroon.Caveat)
    ))
  ,
  DESCRIPTOR = _MACAROON,
  __module__ = 'macaroon_pb2'
  # @@protoc_insertion_point(class_scope:macaroons.Macaroon)
  ))
_sym_db.RegisterMessage(Macaroon)
_sym_db.RegisterMessage(Macaroon.Caveat)


# @@protoc_insertion_point(module_scope)
